# Generated by Django 2.2.5 on 2020-02-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=254, verbose_name='адрес электронной почты пользователя')),
                ('password', models.CharField(max_length=256, verbose_name='пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Pr_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Pr_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('main_pr_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pr_class')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название продукта')),
                ('image', models.FileField(upload_to='products/%Y/%m/%d/')),
                ('slug', models.SlugField()),
                ('description', models.CharField(default='-', max_length=1024, verbose_name='описание продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sub_product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sub_Pr_class', verbose_name='подкласс продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_count', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_count', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название статьи')),
                ('text', models.TextField(verbose_name='текст статьи')),
                ('product', models.ManyToManyField(to='app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='products',
            field=models.ManyToManyField(blank=True, through='app.Cart', to='app.Product'),
        ),
    ]
